name: PartyGames
authors: [SpaceTacos, TrollyLoki]
main: net.spacetacos.partygames.PartyGamesPlugin
version: ${project.version}
api-version: 1.16
depend:
  - MiniGameLibrary
commands:
  partygames:
    aliases:
      - pg
      - erolisgenius
      - factbulldog
      - harrygreatatbuild